name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install wasm-pack
        run: cargo install --git https://github.com/mrbbot/wasm-pack
      - run: npm ci
      - run: npm run build
      - run: npm test
